// Generated by CoffeeScript 1.10.0
(function() {
  var $, Database, Game, Humano, Mosquito, mainView, myApp,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  myApp = new Framework7({
    material: true,
    pushState: true,
    swipePanel: 'left',
    swipePanelActiveArea: 56
  });

  $ = Dom7;

  mainView = myApp.addView('.view-main', {
    dynamicNavbar: true
  });

  Dom7.ajaxSetup({
    beforeSend: function() {
      return myApp.showIndicator();
    },
    complete: function() {
      return myApp.hideIndicator();
    }
  });

  Database = (function() {
    function Database() {
      this.name = "ZikaGame";
      this.version = "1.0";
      this.displayName = "ZikaGame";
      this.maxSize = 65536;
      this.db = openDatabase(this.name, this.version, this.displayName, this.maxSize);
    }

    Database.prototype.sqlExecute = function(query, func, parameters) {
      if (parameters == null) {
        parameters = null;
      }
      return this.db.transaction(function(transaction) {
        return transaction.executeSql(query, parameters, function(transaction, result) {
          return func(result);
        }, function(transaction, error) {
          return alert(error.message);
        });
      });
    };

    return Database;

  })();

  Game = (function(superClass) {
    extend(Game, superClass);

    function Game(paginaContent) {
      this.vida = 100;
      this.window = $(window);
      this.pontosJogo = $(".pontos");
      this.loopGerarConteudo = null;
      if (paginaContent != null) {
        this.paginaContent = paginaContent;
      } else {
        alert("Deu Problema Sério");
      }
    }

    Game.prototype.addVida = function(qtde) {
      return this.vida += qtde;
    };

    Game.prototype.addPontos = function(pontos) {
      return this.pontosJogo.text(parseInt(this.pontosJogo.text()) + pontos);
    };

    Game.prototype.randomTop = function(height) {
      var aleatorio;
      aleatorio = Math.random() * this.window.heigth() + 56;
      if (aleatorio + height >= this.window.height()) {
        return (this.window.height() - height) + "px";
      } else {
        return aleatorio + "px";
      }
    };

    Game.prototype.randomLeft = function(width) {
      var aleatorio;
      aleatorio = Math.random * this.window.width();
      if (aleatorio + width >= this.window.width()) {
        return (this.window.width() - width) + "px";
      } else {
        return aleatorio + "px";
      }
    };

    Game.prototype.pauseContinueJogo = function() {
      clearInterval(this.loopGerarConteudo);
      return this.paginaContent.toggleClass("pause-background");
    };

    return Game;

  })(Database);

  Mosquito = (function(superClass) {
    extend(Mosquito, superClass);

    function Mosquito() {}

    Mosquito.prototype.aparecer = function() {};

    Mosquito.prototype.sumir = function() {};

    Mosquito.prototype.morrer = function() {};

    Mosquito.prototype.reproduzir = function() {};

    Mosquito.prototype.infectar = function() {};

    return Mosquito;

  })(Game);

  Humano = (function(superClass) {
    extend(Humano, superClass);

    function Humano() {}

    Humano.prototype.aparecer = function() {};

    Humano.prototype.sumir = function() {};

    Humano.prototype.morrer = function() {};

    Humano.prototype.proteção = function() {};

    return Humano;

  })(Game);

  myApp.onPageInit("modo-humano", function(page) {
    var game;
    game = new Game($(".modo-humano"));
    $(".pause-continue-game").on("click", function(e) {
      var $this;
      $this = $(this);
      e.preventDefault();
      if ($this.hasClass("pause-game")) {
        return $this.addClass('continue-game').removeClass('pause-game');
      } else {
        return $this.addClass('pause-game').removeClass('continue-game');
      }
    });
  });

}).call(this);

//# sourceMappingURL=Game.js.map
